import assert from 'node:assert/strict'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import {test} from 'node:test'
import {
  derivedDataMappings,
  generateXcconfig,
  isBuild,
  parseInvocation,
  realpathLenient,
  remoteServicePath,
} from './xcodeargs.ts'

test('isBuild', () => {
  assert.equal(isBuild(['-workspace', 'App.xcworkspace', '-scheme', 'App']), true, 'build is the default action')
  assert.equal(isBuild(['-scheme', 'App', 'build']), true)
  assert.equal(isBuild(['-scheme', 'App', 'test']), true)
  assert.equal(isBuild(['-scheme', 'App', 'archive', '-archivePath', 'App.xcarchive']), true)
  assert.equal(isBuild(['-scheme', 'App', '-showBuildSettings']), false)
  assert.equal(isBuild(['-list']), false)
  assert.equal(isBuild(['-version']), false)
  assert.equal(isBuild(['-exportArchive', '-archivePath', 'App.xcarchive']), false)
  assert.equal(isBuild(['-resolvePackageDependencies']), false)
  assert.equal(isBuild(['-scheme', 'App', 'clean']), false, 'a bare clean builds nothing')
  assert.equal(isBuild(['-scheme', 'App', 'clean', 'build']), true)
})

test('parseInvocation rewrites -xcconfig and reads -derivedDataPath', () => {
  const inv = parseInvocation(
    ['-scheme', 'App', '-xcconfig', 'ci.xcconfig', '-derivedDataPath', 'dd', '-xcconfig=last.xcconfig', 'build'],
    '/work',
  )
  assert.deepEqual(inv.args, ['-scheme', 'App', '-derivedDataPath', 'dd', 'build'])
  assert.equal(inv.xcconfig, '/work/last.xcconfig', 'the last -xcconfig wins')
  assert.equal(inv.derivedDataPath, '/work/dd')
})

test('parseInvocation leaves a trailing flag without a value alone', () => {
  const inv = parseInvocation(['build', '-xcconfig'], '/work')
  assert.deepEqual(inv.args, ['build', '-xcconfig'])
  assert.equal(inv.xcconfig, undefined)
})

test('realpathLenient resolves symlinks in paths that do not exist yet', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'xcodeargs-'))
  try {
    const real = path.join(root, 'real')
    fs.mkdirSync(real)
    fs.symlinkSync(real, path.join(root, 'link'))
    assert.equal(
      realpathLenient(path.join(root, 'link', 'dd', 'Build')),
      path.join(fs.realpathSync(real), 'dd', 'Build'),
    )
  } finally {
    fs.rmSync(root, {recursive: true, force: true})
  }
})

test('derivedDataMappings maps the resolved DerivedData path', () => {
  const resolve = (p: string) => p.replace(/^\/tmp\//, '/private/tmp/')
  assert.deepEqual(derivedDataMappings('/tmp/dd', resolve), [
    '/private/tmp/dd/Build/Products=/^symroot',
    '/private/tmp/dd/Build/Intermediates.noindex=/^objroot',
    '/private/tmp/dd=/^dd',
  ])
  assert.deepEqual(derivedDataMappings('/Users/runner/dd', resolve), [], 'no mappings without symlinks')
  assert.deepEqual(derivedDataMappings(undefined, resolve), [])
})

test('generateXcconfig includes Depot first, then the customer', () => {
  const xcconfig = generateXcconfig({
    depotXcconfig: '/var/run/depot-xcode-cache.xcconfig',
    userXcconfig: '/work/ci.xcconfig',
    mappings: ['/private/tmp/dd=/^dd', '/path with space=/^x'],
    swift: true,
  })
  assert.equal(
    xcconfig,
    [
      '// Generated by depot/xcode-compilation-cache.',
      '#include "/var/run/depot-xcode-cache.xcconfig"',
      '#include "/work/ci.xcconfig"',
      'SWIFT_OTHER_PREFIX_MAPPINGS = $(inherited) /private/tmp/dd=/^dd "/path with space=/^x"',
      'CLANG_OTHER_PREFIX_MAPPINGS = $(inherited) /private/tmp/dd=/^dd "/path with space=/^x"',
      '',
    ].join('\n'),
  )
})

test('generateXcconfig without Swift caching', () => {
  const xcconfig = generateXcconfig({depotXcconfig: '/depot.xcconfig', mappings: [], swift: false})
  assert.match(xcconfig, /^SWIFT_ENABLE_COMPILE_CACHE = NO$/m)
  assert.match(xcconfig, /^SWIFT_ENABLE_EXPLICIT_MODULES = NO$/m)
  assert.match(xcconfig, /^COMPILATION_CACHE_REMOTE_SUPPORTED_LANGUAGES = c c\+\+ objective-c objective-c\+\+$/m)
  assert.doesNotMatch(xcconfig, /PREFIX_MAPPINGS/)
})

test('generateXcconfig with remarks', () => {
  const xcconfig = generateXcconfig({depotXcconfig: '/depot.xcconfig', mappings: [], swift: true, remarks: true})
  assert.match(xcconfig, /^COMPILATION_CACHE_ENABLE_DIAGNOSTIC_REMARKS = YES$/m)
  assert.doesNotMatch(generateXcconfig({depotXcconfig: '/depot.xcconfig', mappings: [], swift: true}), /REMARKS/)
})

test('remoteServicePath', () => {
  assert.equal(
    remoteServicePath('A = B\nCOMPILATION_CACHE_REMOTE_SERVICE_PATH = /var/run/depot-xcode-cache.sock\n'),
    '/var/run/depot-xcode-cache.sock',
  )
  assert.equal(remoteServicePath('A = B\n'), undefined)
})
